version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-goriya
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goriya
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: goriya-app
    restart: always
    ports:
      - "8086:8081"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
